Anber/wyw-in-js

examples/template-tag-syntax/.eslintrc.js, examples/template-tag-syntax/babel.config.js, examples/template-tag-syntax/jest.config.js, examples/template-tag-syntax/package.json, examples/template-tag-syntax/processors/css.js, examples/template-tag-syntax/src/CSSProperties.ts, examples/template-tag-syntax/src/__tests__/getTagProcessor.test.ts, examples/template-tag-syntax/src/css.ts, examples/template-tag-syntax/src/index.ts, examples/template-tag-syntax/src/processors/css.ts, examples/template-tag-syntax/tsconfig.eslint.json, examples/template-tag-syntax/tsconfig.json, examples/template-tag-syntax/tsconfig.spec.json, package.json, packages/processor-utils/src/TaggedTemplateProcessor.ts, packages/transform/src/__tests__/utils/getTagProcessor.test.ts, packages/webpack-loader/package.json, pnpm-lock.yaml
=> chore: example of template tag syntax

examples/object-syntax/.eslintrc.js, examples/object-syntax/babel.config.js, examples/object-syntax/jest.config.js, examples/object-syntax/package.json, examples/object-syntax/processors/makeStyles.js, examples/object-syntax/src/__tests__/getTagProcessor.test.ts, examples/object-syntax/src/index.ts, examples/object-syntax/src/makeStyles.ts, examples/object-syntax/src/processors/makeStyles.ts, examples/object-syntax/tsconfig.eslint.json, examples/object-syntax/tsconfig.json, examples/object-syntax/tsconfig.spec.json, examples/template-tag-syntax/src/__tests__/getTagProcessor.test.ts, pnpm-lock.yaml
=> chore: example of object syntax

.gitignore, apps/website/.eslintrc.js, apps/website/next-env.d.ts, apps/website/next.config.js, apps/website/package.json, apps/website/pages/_meta.json, apps/website/pages/bundlers/webpack.mdx, apps/website/pages/how-it-works.mdx, apps/website/pages/index.mdx, apps/website/theme.config.js, apps/website/tsconfig.eslint.json, apps/website/tsconfig.json, apps/website/tsconfig.lib.json, pnpm-lock.yaml, pnpm-workspace.yaml
This PR setups Nextra with some boilterplate in `/apps/website`. It will be used for documentation purposes.
=> docs: setup website and add boilterplate

.changeset/clean-kings-sit.md, packages/vite/.eslintrc.js, packages/vite/babel.config.js, packages/vite/jest.config.js, packages/vite/package.json, packages/vite/src/index.ts, packages/vite/tsconfig.eslint.json, packages/vite/tsconfig.json, packages/vite/tsconfig.lib.json, packages/vite/tsconfig.spec.json, pnpm-lock.yaml
Migration from Linaria's repository.
=> feat(vite): former @linaria/vite

.changeset/fifty-penguins-rule.md, .github/workflows/site-deploy.yml, package.json
https://wyw-in-js.dev should be deployed automatically.
=> chore: site deploy action

.changeset/eight-hounds-leave.md, packages/esbuild/README.md, packages/rollup/README.md, packages/vite/README.md, packages/webpack-loader/README.md
The PR adds a README file for each bundler that we currently have.
=> docs: add README files for every bundler

.changeset/happy-timers-allow.md, packages/vite/src/index.ts
=> fix(vite): handle cases when transforms don't generate CSS

.changeset/perfect-moons-bake.md, packages/transform/src/index.ts
We need this exported to do some code manipulation to support direct props on components. See current [usage](https://github.com/mui/material-ui/blob/master/packages/zero-runtime/src/utils/sxObjectExtractor.ts).
=> feat(transform): export findIdentifiers in public api

.changeset/brave-nails-draw.md, packages/transform/src/transform/generators/__tests__/createStylisProcessor.test.ts, packages/transform/src/transform/generators/createStylisPreprocessor.ts
=> fix(transfrom): global() and nested styles

.changeset/spicy-lobsters-rest.md, examples/template-tag-syntax/package.json, examples/template-tag-syntax/src/css.ts, packages/shared/src/options/types.ts, pnpm-lock.yaml
=> fix(shared): get rid of <reference types="node" />

.changeset/brave-cats-reply.md, packages/esbuild/src/index.ts
webpack and vite already have `debug` option.
=> feat(esbuild): debug mode

.changeset/gentle-worms-rhyme.md, packages/cli/src/wyw-in-js.ts
There was no way to enable debug output in CLI. Fixed.
=> feat(cli): debug option

.changeset/rotten-seahorses-occur.md, packages/processor-utils/src/BaseProcessor.ts, packages/transform/src/utils/getTagProcessor.ts
closes #75 
Author can modify the AST at the end of the process by providing the replacement argument as a function:
For example, move the prop to last
```js
this.replacer((tagPath) => {
const jsxElement = tagPath.parentPath.parentPath.parentPath; // this is a simple implementation
let sxAttribute;
jsxElement.get('attributes').forEach(attr => {
if (attr.node?.name?.name === 'sx') {
sxAttribute = attr;
attr.remove();
}
})
jsxElement.node.attributes.push(sxAttribute.node);
return transformedExpression;
}, false)
```
=> support `replacement` as a function

apps/website/pages/how-to/custom-tagged-template.mdx
=> docs: fix backtick to correct the format

packages/transform/src/utils/traversalCache.ts
The `traverseCache` is no longer in use.
=> refactor(transform): remove unused code

.changeset/eight-tools-sell.md, packages/transform/package.json, pnpm-lock.yaml
We need to bump `happy-dom` to the latest (15.11.0), see #108.
Bumps `happy-dom` to 13.10.1.
=> chore: bump happy-dom to 13.10.1

.changeset/great-tips-punch.md, packages/transform/package.json, packages/transform/src/__tests__/vm/createVmContext.test.ts, packages/transform/src/vm/createVmContext.ts, pnpm-lock.yaml
We need to bump `happy-dom` to the latest (15.11.0), fixes #108.
Bumps `happy-dom` to 15.11.0.
=> chore: bump happy-dom to 15.11.0

apps/website/pages/how-it-works.mdx
Add "how it works". Please feel free to correct me if anything is incorrect.
=> docs: how it works

.github/workflows/check-crates.yml
Adds a workflow that runs tests & build for Rust code.
=> chore: run CI for crates

.changeset/lemon-bulldogs-sparkle.md, apps/website/pages/configuration.mdx, packages/shared/src/index.ts, packages/shared/src/options/types.ts, packages/transform/src/__tests__/__snapshots__/preeval.test.ts.snap, packages/transform/src/__tests__/preeval.test.ts, packages/transform/src/plugins/preeval.ts, packages/transform/src/utils/removeDangerousCode.ts, pnpm-lock.yaml
This pull request introduces a new feature for removing specific Higher-Order Components (HOCs) and components with explicit types during evaluation.
A few new tests were added.
=> Configurable code remover

.changeset/wicked-icons-report.md, packages/transform/src/__tests__/__fixtures__/prepare-code-test-cases/unsupported-dynamic-import/input.ts, packages/transform/src/__tests__/__snapshots__/prepareCode.test.ts.snap, packages/transform/src/plugins/dynamic-import.ts
=> fix(transform): move check for unsupported dynamic imports to eval stage
