configs/jest/index.js
configs/jest/jest-preset.js
configs/jest/package.json
configs/jest/turbo.json
examples/object-syntax/jest.config.js
examples/object-syntax/package.json
examples/object-syntax/tsconfig.eslint.json
examples/object-syntax/tsconfig.json
examples/object-syntax/tsconfig.lib.json
examples/object-syntax/tsconfig.spec.json
examples/template-tag-syntax/jest.config.js
examples/template-tag-syntax/package.json
packages/processor-utils/jest.config.js
packages/processor-utils/package.json
packages/shared/package.json
packages/transform/jest.config.js
packages/transform/package.json
packages/transform/src/utils/findPackageJSON.ts
packages/webpack-loader/jest.config.js
packages/webpack-loader/package.json
pnpm-lock.yaml
tsconfig.aliases.json

Follow up for #4. Enables TS aliases in Jest, so packages rebuilds are not needed anymore 🎉 
- Creates `@wyw-in-js/jest-preset` to store preset
- Modifies `jest.config.js` files to consume new preset
- Updates `package.json` files of examples: removes redundant fields (we don't publish these packages) and points `tags` to source
- Adds ugly fix to `packages/transform/src/utils/findPackageJSON.ts` to workaround a problem with Jest resolver (Jest issue to be reported)

chore: setup aliases in Jest

---

.changeset/famous-radios-doubt.md
packages/rollup/.eslintrc.js
packages/rollup/babel.config.js
packages/rollup/jest.config.js
packages/rollup/package.json
packages/rollup/src/index.ts
packages/rollup/tsconfig.eslint.json
packages/rollup/tsconfig.json
packages/rollup/tsconfig.lib.json
packages/rollup/tsconfig.spec.json
packages/transform/src/index.ts
pnpm-lock.yaml

Migration from Linaria's repository.

feat(rollup): former @linaria/rollup

---

.changeset/weak-owls-rule.md
packages/esbuild/.eslintrc.js
packages/esbuild/babel.config.js
packages/esbuild/jest.config.js
packages/esbuild/package.json
packages/esbuild/src/index.ts
packages/esbuild/tsconfig.eslint.json
packages/esbuild/tsconfig.json
packages/esbuild/tsconfig.lib.json
packages/esbuild/tsconfig.spec.json
pnpm-lock.yaml

Migration from Linaria's repository.

feat(esbuild): former @linaria/esbuild

---

packages/transform/src/transform/helpers/loadLinariaOptions.ts

Backports a fix from https://github.com/callstack/linaria/pull/1370.
See https://github.com/callstack/linaria/issues/1367 for context.

fix(transform): fix detection of export/import statements

---

.changeset/sweet-brooms-doubt.md
packages/cli/bin/wyw-in-js.js

CLI didn't install the bin file. Fixed.

fix: add missed executable

---

.github/workflows/main.yml

Currently the workflow runs for issues & PRs. However, functionality for PRs is unused while it fails on PRs from contributors:

chore: label only issues

---

.changeset/two-zoos-smoke.md
packages/transform/src/__tests__/__snapshots__/shaker.test.ts.snap
packages/transform/src/__tests__/shaker.test.ts
packages/transform/src/plugins/shaker.ts

In some cases, Shaker keeps usages of variables alive even though their bindings are removed. 
One new test was added.

fix(transform): remove constant violations with their bindings

---

.changeset/afraid-countries-walk.md
packages/webpack-loader/src/index.ts

Exports `LoaderOptions` type from `@wyw-in-js/webpack-loader`, fixes #28.

feat(webpack-loader): export LoaderOptions

---

configs/ts/aliases.json
configs/ts/base.json
e2e/vite/fixture.css
e2e/vite/index.html
e2e/vite/package.json
e2e/vite/scripts/test.cjs
e2e/vite/src/index.ts
e2e/vite/tsconfig.json
examples/object-syntax/package.json
examples/object-syntax/processors/makeStyles.js
examples/template-tag-syntax/package.json
examples/template-tag-syntax/processors/css.js
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

This PR adds a simple E2E test for Vite to ensure that CSS gets build properly.

chore: add E2E test for Vite

---

.changeset/nice-dingos-peel.md
packages/transform/src/index.ts
packages/transform/src/transform/generators/__tests__/createStylisProcessor.test.ts
packages/transform/src/transform/generators/createStylisPreprocessor.ts
packages/transform/src/transform/generators/extract.ts

See https://github.com/callstack/linaria/issues/1388.
This PR adds a plugin to handle `:global()` behavior.
Tests have been added. I tested also Linaria docs build.

feat(transform): add stylis plugin to handle ":global()"

---

.changeset/angry-pugs-sparkle.md
packages/esbuild/package.json

ESM should have `mjs` as a file extension.

fix(esbuild): mjs extensions in esm build

---

.changeset/serious-carpets-float.md
packages/rollup/src/index.ts

See #38
The check is no longer needed since it was added when the Vite plugin was just introduced in Linaria.

fix(rollup): remove broken "is it vite?" check

---

.changeset/empty-poets-kick.md
packages/shared/src/findPackageJSON.ts

See #43 
`require` can't resolve ESM-only packages. We can use the `resolve` package here, but it does not solve all cases because `pkgName` can be an alias and should be resolved by a bundler. However, we can't use `resolve` from a bundler because it is async. The good news is that in that specific case, we can just ignore those packages. For now.

fix(shared): crash while resolving esm-only package

---

.changeset/quick-bulldogs-lick.md
apps/website/pages/bundlers/esbuild.mdx
packages/esbuild/src/index.ts

A well-maintained code base can have styles only in specific files (e.g., `Button.styles.ts`). By default, wyw processes all files in an attempt to find styles for extraction. The new option `filter` allows to limit such useless work.
For now, `filter` has been introduced only for `esbuild`.

feat(esbuild): filter option that allows to process only specific files

---

.changeset/nine-vans-drive.md
packages/transform/src/transform/generators/__tests__/createStylisProcessor.test.ts
packages/transform/src/transform/generators/createStylisPreprocessor.ts

Originally in Linaria, keyframes were scoped. This behaviour was broken during migration to Stylis@4.
The old behaviour has been restored. Also, support for the `:global` selector in keyframes has been added.
A few new tests were added.

feat(transform): scoped keyframes

---

.changeset/stale-stingrays-judge.md
packages/transform/src/transform/Entrypoint.helpers.ts
packages/transform/src/utils/getTagProcessor.ts

I found out that an object spread can be extremely slow. Even slower than AST traverse and file operations. `getTagProcessor` now works 10 times faster.

feat(transform): replace object spread with Proxy in getTagProcessor

---

.changeset/quiet-zoos-hang.md
packages/transform/src/transform/generators/__tests__/createStylisProcessor.test.ts
packages/transform/src/transform/generators/createStylisPreprocessor.ts

Suffixer didn't work when keyframes were defined before usages.
Fixed.
A couple of new tests were added.

fix(transform): fix animation name suffixer

---

.changeset/few-dolphins-unite.md
apps/website/pages/configuration.mdx
packages/processor-utils/src/utils/getClassNameAndSlug.ts
packages/shared/src/options/types.ts

we use `index` in default `slugify` but not available for custom `classNameSlug`, this change expose `index` so we can achieve the same as default behaviour, we need it as we need to build it from another folder for website while the `relativeFilename` is different, so I have to normalise it to be the same as build from the lib

feat(processor-utils): Add `index` to ClassNameSlugVars

---

.changeset/weak-yaks-call.md
packages/shared/src/options/types.ts
packages/transform/src/__tests__/module.test.ts
packages/transform/src/__tests__/shaker.test.ts
packages/transform/src/module.ts
packages/transform/src/transform/helpers/loadWywOptions.ts

This PR tries to address this [issue](https://github.com/callstack/linaria/issues/1352) conditionally when it occurs too frequently. This is not a proper fix but a work around at the cost of memory consumption. 
This works by introducing a new feature flag `useWeakRefInEval` that is true by default. If someone wants, they can set it to `false` in their `wyw-in-js` config to disable the usage of `WeakRef`.
I tested locally in a fairly moderate example Pigment CSS repo. I can add tests on guidance.

feat(transform): allow non-usage of WeakRef in Module conditionally

---

.changeset/gold-bags-fry.md
packages/vite/package.json
packages/vite/src/index.ts
pnpm-lock.yaml

Also remove dependency on @rollup/plugin-utils
This PR fixes an [issue](https://github.com/mui/material-ui/issues/41628) related to Vite plugin originally opened on Pigment CSS repo.
This change avoids the usage of css content slug in the filename and keeps the css filename unique just by using the path of the original js/ts file and using `wyw-in-js` prefix before the extension.
Using slug had an issue where if you removed a css property from your css definition, it would get applied in a new `style` tag during dev mode. Thus also keeping the old css in place which would result in overall css being applied from both old and new css content.
The fix instead keeps using the same filename regardless of the content and just pings the FE to reload the latest CSS content which it replaces in …

fix(vite): Fix CSS replacement in Vite HMR

---

.changeset/nasty-eagles-camp.md
packages/processor-utils/src/utils/types.ts
packages/transform/src/plugins/collector.ts
packages/transform/src/plugins/preeval.ts
packages/transform/src/utils/getTagProcessor.ts

Linaria's `styled` processor needs a list of extensions from the config.  #1405
Only types were changed.

feat(processor-utils): pass `extensions` option to processors

---

.changeset/slimy-bulldogs-dress.md
packages/transform/src/transform/generators/__tests__/createStylisProcessor.test.ts
packages/transform/src/transform/generators/createStylisPreprocessor.ts

Support for `@media` selectors inside `:global()` selectors.
```
:global() {
@media (prefers-color-scheme: dark) {
html {
color-scheme: dark;
}
}
}
```
The new test was added.

fix(transform): support for @media selectors inside :global

---

packages/shared/src/findPackageJSON.ts

#92
- Access `process` from `globalThis` to support non-node runtime
- Add null check to `process.env`
1. Reproduce #92 on https://github.com/AsukaCHikaru/wyw-in-js-vite-env-issue
2. Execute `npm run build` on this PR
3. Copy `packages/shared/lib/findPackageJSON.js` to `node_modules/.deno/@wyw-in-js+shared@0.5.3/node_modules/@wyw-in-js/shared/lib/findPackageJSON.js`
4. Execute `deno task dev` and access `localhost:5173`

fix(shared): process.env is undefined on non-node runtime issue

---

.changeset/dry-cobras-check.md
packages/shared/src/index.ts

When importing from WyW packages from within a Vite environment, the following error occurs:
```
✘ [ERROR] No matching export in "node_modules/.pnpm/@wyw-in-js+shared@0.5.4/node_modules/@wyw-in-js/shared/esm/IVariableContext.js" for import "IVariableContext"
node_modules/.pnpm/@wyw-in-js+shared@0.5.4/node_modules/@wyw-in-js/shared/esm/index.js:6:9:
6 │ export { IVariableContext } from './IVariableContext';
╵          ~~~~~~~~~~~~~~~~
```
It appears that `IVariableContext` is being re-exported as if it were a variable available at runtime:
https://github.com/Anber/wyw-in-js/blob/d3c2791adacd7c20e8ace2417fae5aab5fce7814/packages/shared/src/index.ts#L7
However, the [file referenced in the ESM distribution](https://unpkg.com/browse/@wyw-in-js/shared@0.5.4/esm/IVariableContext.js) doesn’t …

fix(shared): invalid export of interface
